CREATE DATABASE IF NOT EXISTS student_planner
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;
USE student_planner;

-- USERS
CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(190) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
role ENUM('admin','student') NOT NULL DEFAULT 'student',
is_active TINYINT(1) NOT NULL DEFAULT 1,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
last_login_at DATETIME NULL,
INDEX (email)
) ENGINE=InnoDB;

-- SESSIONS this is optional, and not personally used in brainbow
CREATE TABLE sessions (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
session_token CHAR(64) NOT NULL UNIQUE,
ip VARCHAR(45) NULL,
user_agent VARCHAR(255) NULL,
expires_at DATETIME NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- PROJECTS
CREATE TABLE projects (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
owner_id INT UNSIGNED NOT NULL,
title VARCHAR(150) NOT NULL,
description TEXT NULL,
course_code VARCHAR(30) NULL,
color VARCHAR(9) NULL,
is_archived TINYINT(1) NOT NULL DEFAULT 0,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
INDEX (owner_id),
INDEX (is_archived)
) ENGINE=InnoDB;


CREATE TABLE todos (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
title VARCHAR(200) NOT NULL,
description TEXT NULL,
status ENUM('todo','doing','done') NOT NULL DEFAULT 'todo',
priority TINYINT NOT NULL DEFAULT 0,
due_date DATE NULL,
created_by INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_todos_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_todos_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
INDEX (project_id, status, priority, due_date)
) ENGINE=InnoDB;

CREATE TABLE notes (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
title VARCHAR(200) NOT NULL,
content MEDIUMTEXT NOT NULL,
is_pinned TINYINT(1) NOT NULL DEFAULT 0,
created_by INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_notes_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_notes_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
FULLTEXT KEY ft_notes_content (title, content)
) ENGINE=InnoDB;

-- EVENTS (calendar)
CREATE TABLE events (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
title VARCHAR(200) NOT NULL,
description TEXT NULL,
start_datetime DATETIME NOT NULL,
end_datetime DATETIME NULL,
all_day TINYINT(1) NOT NULL DEFAULT 0,
location VARCHAR(200) NULL,
created_by INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_events_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_events_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
INDEX (project_id, start_datetime)
) ENGINE=InnoDB;

-- MIND MAPS
CREATE TABLE mindmaps (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
title VARCHAR(200) NOT NULL,
data_json JSON NOT NULL,
thumbnail_path VARCHAR(255) NULL,
created_by INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_mm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_mm_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
INDEX (project_id, updated_at)
) ENGINE=InnoDB;

-- WHITEBOARDS
CREATE TABLE whiteboards (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
title VARCHAR(200) NOT NULL,
data_json JSON NOT NULL,
thumbnail_path VARCHAR(255) NULL,
created_by INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_wb_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_wb_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
INDEX (project_id, updated_at)
) ENGINE=InnoDB;

-- TAGS this is optional, and not personally used in brainbow
CREATE TABLE tags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(60) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- this is optional, and not personally used in brainbow
CREATE TABLE item_tags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tag_id INT UNSIGNED NOT NULL,
item_type ENUM('todo','note','mindmap','whiteboard','event') NOT NULL,
item_id INT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_it_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
INDEX ix_item (item_type, item_id)
) ENGINE=InnoDB;

-- PROJECT MEMBERS this is optional, and not personally used in brainbow
CREATE TABLE project_members (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
project_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
role ENUM('owner','editor','viewer') NOT NULL DEFAULT 'editor',
added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY uq_member (project_id, user_id),
CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Adding another column to users table
ALTER TABLE users
ADD login_count INT NOT NULL DEFAULT 0;